const zoning_districts = {
  "RF-2": {
    "max_density": 97.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": 13
  },
  "TOD-1": {
    "max_density": 90,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": 12
  },
  "B-4": {
    "max_density": 45,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": 6,
    "height_limit_feet": "4:1 ip",
    "height_limit_stories": ""
  },
  "RF-1": {
    "max_density": 45,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": 6
  },
  "B-5": {
    "max_density": 37.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": 5
  },
  "B-7": {
    "max_density": 37.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": 5
  },
  "B-6": {
    "max_density": 30,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": 4
  },
  "B-2": {
    "max_density": 22.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": 35,
    "height_limit_stories": ""
  },
  "B2-POD": {
    "max_density": 22.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "HO": {
    "max_density": 22.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": 4.6,
    "height_limit_feet": "3:1 ip",
    "height_limit_stories": ""
  },
  "RO-3": {
    "max_density": 22.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": 4.6,
    "height_limit_feet": "ip",
    "height_limit_stories": ""
  },
  "UB-2": {
    "max_density": 22.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": 3
  },
  "UB2-PE8": {
    "max_density": 22.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "B-1": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": 25,
    "height_limit_stories": ""
  },
  "B-3": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": 2,
    "height_limit_feet": 35,
    "height_limit_stories": ""
  },
  "R-73": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": 2,
    "height_limit_feet": "2:1 ip 150 feet",
    "height_limit_stories": ""
  },
  "UB": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": 28,
    "height_limit_stories": ""
  },
  "UB-PE2": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "UB-PE3": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "UB-PE4": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "UB-PE5": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "UB-PE6": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "UB-PE7": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "UB-PO1": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "UB-PO2": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "UB-PO3": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "UB-PO4": {
    "max_density": 15,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "R-63": {
    "max_density": 7.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "1 DU per 1000 sq ft",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": 3
  },
  "R-53": {
    "max_density": 6,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "1 DU per 1250 sq ft",
    "max_far": "",
    "height_limit_feet": 35,
    "height_limit_stories": ""
  },
  "RO2-PE2": {
    "max_density": 6,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "1 DU per 1250 sq ft",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "RO2-PE5": {
    "max_density": 6,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "1 DU per 1250 sq ft",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "RO-2": {
    "max_density": 6,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "1 DU per 1250 sq ft",
    "max_far": "",
    "height_limit_feet": 35,
    "height_limit_stories": ""
  },
  "R-48": {
    "max_density": 3.27,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "1 DU per 2200 sq ft",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": 35
  },
  "R-43": {
    "max_density": 2.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "1 DU per 3000 sq ft",
    "max_far": "",
    "height_limit_feet": 35,
    "height_limit_stories": ""
  },
  "RO-1": {
    "max_density": 2.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "1 DU per 3000 sq ft",
    "max_far": "",
    "height_limit_feet": 25,
    "height_limit_stories": ""
  },
  "R-7": {
    "max_density": 2,
    "residential_banned": false,
    "two_family_max": "TRUE",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": 4400,
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "R-8": {
    "max_density": 2,
    "residential_banned": false,
    "two_family_max": "TRUE",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": 3400,
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "R-6": {
    "max_density": 1.722,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": 6000,
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "R-MH": {
    "max_density": 1.4,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "8 DU per acre",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "I": {
    "max_density": 1.25,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": "same as R-5?",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "ip",
    "height_limit_stories": ""
  },
  "R-5": {
    "max_density": 1.25,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": 6000,
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "R-4": {
    "max_density": 1,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": 7500,
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "R-3": {
    "max_density": 0.75,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": 10000,
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "R-2": {
    "max_density": 0.5,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": 15000,
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "R-1": {
    "max_density": 0.375,
    "residential_banned": false,
    "two_family_max": "",
    "single_family_min_lot_size": 20000,
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "CM": {
    "max_density": 0,
    "residential_banned": true,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "DCC": {
    "max_density": 0,
    "residential_banned": true,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "M-1": {
    "max_density": 0,
    "residential_banned": true,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "M-2": {
    "max_density": 0,
    "residential_banned": true,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "OS": {
    "max_density": 0,
    "residential_banned": true,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  },
  "RP": {
    "max_density": 0,
    "residential_banned": true,
    "two_family_max": "",
    "single_family_min_lot_size": "",
    "two_family_min_lot_size": "",
    "density_limit": "",
    "max_far": "",
    "height_limit_feet": "",
    "height_limit_stories": ""
  }
}